/**
 * The seed catalogue: imported beauty, mostly fragrance from the UAE plus
 * Korean skincare, Italian colour and Moroccan bath rituals.
 *
 * Prices are INR. `mrp` is the pre-discount price (struck through in the UI).
 * Brand names here are invented for the demo so nothing real is misrepresented.
 */

export const CATEGORIES = [
  {
    slug: 'fragrance',
    name: 'Fragrance',
    tagline: 'Oud, attar & eau de parfum',
    blurb: 'Deep ouds and rose attars sourced from the perfume souks of Deira and Sharjah.',
    image: '/images/categories/fragrance.jpg',
  },
  {
    slug: 'skincare',
    name: 'Skincare',
    tagline: 'Serums, creams & facial oils',
    blurb: 'K-beauty barrier care and French botanicals, shipped cold-chain where it matters.',
    image: '/images/categories/skincare.jpg',
  },
  {
    slug: 'makeup',
    name: 'Makeup',
    tagline: 'Lips, complexion & colour',
    blurb: 'Milanese colour houses — pigment-dense formulas built for Indian undertones.',
    image: '/images/categories/makeup.jpg',
  },
  {
    slug: 'bath-body',
    name: 'Bath & Body',
    tagline: 'Hammam rituals & body oils',
    blurb: 'Argan, black soap and mineral soaks from Marrakech and the Levant.',
    image: '/images/categories/bath-body.jpg',
  },
  {
    slug: 'gifting',
    name: 'Gifting',
    tagline: 'Sets, minis & discovery boxes',
    blurb: 'Curated boxes that land wrapped, with a handwritten note if you ask.',
    image: '/images/categories/gifting.jpg',
  },
]

/** Seller storefronts. `password` is plain here; the seeder hashes it. */
export const SELLERS = [
  {
    key: 'attar',
    name: 'Farhan Qureshi',
    email: 'seller@lumiere.in',
    password: 'seller123',
    storeName: 'Attar House Dubai',
    storeSlug: 'attar-house-dubai',
    storeBio:
      'Third-generation attar traders working out of the Deira perfume souk. We hand-carry every batch through Mumbai customs, so what reaches you is the same juice sold on Sikkat Al Khail Street — never a reformulated export batch.',
    city: 'Deira, Dubai',
    country: 'United Arab Emirates',
    phone: '+971 50 442 1180',
    rating: 4.8,
    since: 2016,
  },
  {
    key: 'seoul',
    name: 'Priya Nair',
    email: 'seoul@lumiere.in',
    password: 'seller123',
    storeName: 'Seoul Skin Atelier',
    storeSlug: 'seoul-skin-atelier',
    storeBio:
      'We fly Korean barrier-care in twice a month and refuse anything with under fourteen months of shelf life left. Every carton is batch-photographed before it leaves Incheon.',
    city: 'Bandra West, Mumbai',
    country: 'India (imports from South Korea)',
    phone: '+91 98204 33712',
    rating: 4.9,
    since: 2019,
  },
  {
    key: 'noir',
    name: 'Camille Rousseau',
    email: 'noir@lumiere.in',
    password: 'seller123',
    storeName: 'Maison Noir',
    storeSlug: 'maison-noir',
    storeBio:
      'A small Paris-and-Milan buying house. We work directly with independent perfumers in Grasse and colour labs in Lombardy, then clear a single consolidated shipment into Delhi each month.',
    city: 'Le Marais, Paris',
    country: 'France',
    phone: '+33 6 12 88 40 21',
    rating: 4.7,
    since: 2021,
  },
]

const g = (...slugs) => slugs.map((s) => `/images/products/${s}.jpg`)

/**
 * `variants` carry their own price so the PDP size chips behave like a real
 * store. The card price shown in listings is the cheapest variant.
 */
export const PRODUCTS = [
  // ───────────────────────── Fragrance ─────────────────────────
  {
    slug: 'oud-mood-elixir',
    name: 'Oud Mood Elixir',
    brand: 'Lattafa Shabab',
    seller: 'attar',
    category: 'fragrance',
    origin: 'Deira, Dubai · UAE',
    tagline: 'Smoky oud, saffron and a long amber drydown',
    description:
      'The bottle that made half of Deira smell the same in 2019, and still the easiest oud to wear if you have never worn one. Saffron and nutmeg open sharp, then twenty minutes in it settles into resinous agarwood over amber and a soft leather base. Projection is generous for the first three hours — one spray to the chest is genuinely enough in Indian summer.',
    notes: { top: 'Saffron, Nutmeg', heart: 'Agarwood, Rose', base: 'Amber, Leather, Musk' },
    howToUse:
      'Spray once at the base of the throat and once on the wrist, never rubbed — friction flattens the saffron. In humidity above 70% a single spray carries all day.',
    ingredients:
      'Alcohol Denat., Parfum (Fragrance), Aqua, Ethylhexyl Methoxycinnamate, Butyl Methoxydibenzoylmethane, Linalool, Coumarin, Eugenol.',
    images: g('oud-mood-elixir', 'oud-al-layl', 'mystique-noir', 'sandalwood-sillage'),
    variants: [
      { label: '10 ml travel', price: 1299, mrp: 1699, stock: 64 },
      { label: '50 ml', price: 2999, mrp: 3899, stock: 28 },
      { label: '100 ml', price: 4299, mrp: 5499, stock: 17 },
    ],
    badges: ['Best seller'],
    concern: ['Evening wear', 'Long lasting'],
    rating: 4.7,
    reviewCount: 214,
  },
  {
    slug: 'amber-oud-rouge',
    name: 'Amber Oud Rouge',
    brand: 'Al Haramain',
    seller: 'attar',
    category: 'fragrance',
    origin: 'Dubai · UAE',
    tagline: 'Sweet raspberry-amber, absurd longevity',
    description:
      'A gourmand oud that leans candied rather than medicinal. Raspberry and bergamot up top read almost like a dessert, but the agarwood underneath keeps it from turning juvenile. Fourteen-hour wear is normal; testers routinely report smelling it on a shirt after a wash.',
    notes: { top: 'Raspberry, Bergamot', heart: 'Oud, Jasmine', base: 'Amber, Vanilla, Tonka' },
    howToUse: 'Two sprays maximum. This one blooms for a full hour before it settles — do not over-apply on first wear.',
    ingredients: 'Alcohol Denat., Parfum (Fragrance), Aqua, Benzyl Salicylate, Limonene, Linalool, Citral.',
    images: g('amber-oud-rouge', 'royal-oud-noir', 'oud-al-layl', 'mystique-noir'),
    variants: [
      { label: '60 ml', price: 5499, mrp: 6999, stock: 21 },
      { label: '100 ml', price: 6899, mrp: 8999, stock: 12 },
    ],
    badges: ['Editor’s pick'],
    concern: ['Evening wear', 'Gifting'],
    rating: 4.8,
    reviewCount: 341,
  },
  {
    slug: 'royal-oud-noir',
    name: 'Royal Oud Noir',
    brand: 'Ard Al Zaafaran',
    seller: 'attar',
    category: 'fragrance',
    origin: 'Sharjah · UAE',
    tagline: 'Rose and oud, the classic Khaleeji pairing',
    description:
      'Taif rose laid over dry Cambodian-style oud — the pairing every Gulf house attempts and this one gets right at the price. It opens loudly floral and dries down woody and slightly dusty, in the way good oud should. A safe first oud for anyone nervous about the barnyard note cheap agarwood can carry.',
    notes: { top: 'Taif Rose, Pink Pepper', heart: 'Oud, Patchouli', base: 'Sandalwood, Musk' },
    howToUse: 'Best on fabric — the rose lasts noticeably longer on a dupatta or collar than on skin.',
    ingredients: 'Alcohol Denat., Parfum (Fragrance), Aqua, Geraniol, Citronellol, Linalool, Eugenol.',
    images: g('royal-oud-noir', 'fleur-de-lumiere', 'rose-attar-absolute', 'amber-oud-rouge'),
    variants: [
      { label: '50 ml', price: 2499, mrp: 3299, stock: 40 },
      { label: '100 ml', price: 3299, mrp: 4199, stock: 26 },
    ],
    badges: [],
    concern: ['Daily wear'],
    rating: 4.5,
    reviewCount: 128,
  },
  {
    slug: 'musk-al-ghazal',
    name: 'Musk Al Ghazal',
    brand: 'Swiss Arabian',
    seller: 'attar',
    category: 'fragrance',
    origin: 'Dubai · UAE',
    tagline: 'Clean white musk — the office-safe one',
    description:
      'Powdery white musk with a touch of rose and heliotrope. This is the fragrance to reach for when oud is too much: it sits close to the skin, reads clean rather than perfumed, and nobody in a meeting will ask what you are wearing. Popular as a layering base under heavier attars.',
    notes: { top: 'Aldehydes, Rose', heart: 'White Musk, Heliotrope', base: 'Cedar, Vanilla' },
    howToUse: 'Layer one spray under an oud to soften it, or wear alone for a clean, close skin scent.',
    ingredients: 'Alcohol Denat., Parfum (Fragrance), Aqua, Hydroxycitronellal, Linalool, Benzyl Benzoate.',
    images: g('musk-al-ghazal', 'velvet-bloom', 'rose-quartz-mist', 'nuit-blanche'),
    variants: [
      { label: '50 ml', price: 2749, mrp: 3499, stock: 55 },
      { label: '100 ml', price: 3999, mrp: 4999, stock: 30 },
    ],
    badges: [],
    concern: ['Daily wear', 'Office safe'],
    rating: 4.4,
    reviewCount: 96,
  },
  {
    slug: 'rose-attar-absolute',
    name: 'Rose Attar Absolute',
    brand: 'Ajmal Heritage',
    seller: 'attar',
    category: 'fragrance',
    origin: 'Dubai · UAE',
    tagline: 'Alcohol-free rose oil in a 12 ml roller',
    description:
      'A true attar — rose absolute carried in sandalwood oil, no alcohol anywhere in it. Thick, almost syrupy on the skin, and it develops for hours rather than minutes. Because there is no alcohol it never bites on application, which makes it the one most people with sensitive skin end up keeping.',
    notes: { top: 'Rose Absolute', heart: 'Rose Otto, Geranium', base: 'Mysore-style Sandalwood' },
    howToUse: 'Warm a single dab between the fingers, then press — do not rub — into the pulse points.',
    ingredients: 'Santalum Album Oil, Rosa Damascena Flower Oil, Pelargonium Graveolens Oil, Geraniol, Citronellol.',
    images: g('rose-attar-absolute', 'fleur-de-lumiere', 'royal-oud-noir', 'oud-mood-elixir'),
    variants: [
      { label: '6 ml roller', price: 4200, mrp: 5100, stock: 18 },
      { label: '12 ml roller', price: 7499, mrp: 9200, stock: 9 },
    ],
    badges: ['Alcohol-free'],
    concern: ['Sensitive skin', 'Gifting'],
    rating: 4.9,
    reviewCount: 187,
  },
  {
    slug: 'citrus-oud-28',
    name: 'Citrus Oud 28',
    brand: 'Maison Noir',
    seller: 'noir',
    category: 'fragrance',
    origin: 'Grasse · France',
    tagline: 'Bergamot over agarwood — oud for hot weather',
    description:
      'An unusual construction: bright Calabrian bergamot and grapefruit sitting directly on top of agarwood, with almost no floral bridge between them. The contrast is the point. It reads fresh for the first hour and woody for the next six, which makes it one of the few ouds that works in April in Delhi.',
    notes: { top: 'Calabrian Bergamot, Grapefruit', heart: 'Agarwood, Cardamom', base: 'Vetiver, Ambergris' },
    howToUse: 'Three sprays — the citrus burns off fast and this one is built to be applied generously.',
    ingredients: 'Alcohol Denat., Parfum (Fragrance), Aqua, Limonene, Linalool, Citral, Geraniol.',
    images: g('citrus-oud-28', 'sandalwood-sillage', 'nuit-blanche', 'mystique-noir'),
    variants: [
      { label: '50 ml', price: 6900, mrp: 8200, stock: 14 },
      { label: '100 ml', price: 8900, mrp: 10500, stock: 7 },
    ],
    badges: ['New in'],
    concern: ['Daily wear', 'Summer'],
    rating: 4.6,
    reviewCount: 63,
  },
  {
    slug: 'velvet-bloom',
    name: 'Velvet Bloom EDP',
    brand: 'Lumière Atelier',
    seller: 'noir',
    category: 'fragrance',
    origin: 'Paris · France',
    tagline: 'Peony, lychee and a clean musk finish',
    description:
      'Soft pink florals without the hairspray effect that sinks most peony scents. Lychee keeps the opening juicy, peony and freesia carry the middle, and a clean musk base stops it turning powdery. Moderate projection, roughly six hours of wear.',
    notes: { top: 'Lychee, Mandarin', heart: 'Peony, Freesia', base: 'White Musk, Cedar' },
    howToUse: 'Spray onto moisturised skin — florals this light fade fast on dry skin.',
    ingredients: 'Alcohol Denat., Parfum (Fragrance), Aqua, Linalool, Limonene, Alpha-Isomethyl Ionone.',
    images: g('velvet-bloom', 'fleur-de-lumiere', 'musk-al-ghazal', 'rose-quartz-mist'),
    variants: [
      { label: '30 ml', price: 2699, mrp: 3400, stock: 33 },
      { label: '50 ml', price: 3899, mrp: 4800, stock: 22 },
    ],
    badges: [],
    concern: ['Daily wear', 'Office safe'],
    rating: 4.3,
    reviewCount: 88,
  },
  {
    slug: 'nuit-blanche',
    name: 'Nuit Blanche Extrait',
    brand: 'Maison Noir',
    seller: 'noir',
    category: 'fragrance',
    origin: 'Grasse · France',
    tagline: 'Tuberose and incense, 30% concentration',
    description:
      'An extrait, not an EDP — the oil load is roughly triple a normal spray, and it behaves accordingly. Narcotic tuberose over frankincense and a smear of styrax. Two sprays is a statement; three is a decision. Best kept for cold evenings and rooms you intend to be remembered in.',
    notes: { top: 'Pink Pepper, Bergamot', heart: 'Tuberose, Orange Blossom', base: 'Frankincense, Styrax, Vanilla' },
    howToUse: 'One spray, on clothing rather than skin. Reapplication is almost never necessary.',
    ingredients: 'Alcohol Denat., Parfum (Fragrance), Aqua, Benzyl Salicylate, Benzyl Benzoate, Farnesol, Linalool.',
    images: g('nuit-blanche', 'mystique-noir', 'citrus-oud-28', 'velvet-bloom'),
    variants: [
      { label: '15 ml', price: 5400, mrp: 6400, stock: 16 },
      { label: '50 ml', price: 9400, mrp: 11800, stock: 5 },
    ],
    badges: ['Limited stock'],
    concern: ['Evening wear', 'Long lasting'],
    rating: 4.8,
    reviewCount: 71,
  },
  {
    slug: 'sandalwood-sillage',
    name: 'Sandalwood Sillage',
    brand: 'Ajmal Heritage',
    seller: 'attar',
    category: 'fragrance',
    origin: 'Dubai · UAE',
    tagline: 'Creamy sandalwood, almost no sweetness',
    description:
      'Dry, milky sandalwood with cardamom and a whisper of iris. There is no vanilla propping this up, which is rarer than it sounds — most sandalwood scents sweeten the wood until it disappears. This one stays woody from first spray to last, and layers beautifully over the rose attar.',
    notes: { top: 'Cardamom, Pink Pepper', heart: 'Sandalwood, Iris', base: 'Cedar, Dry Musk' },
    howToUse: 'Excellent as a layering base. One spray under any rose or oud scent adds hours of drydown.',
    ingredients: 'Alcohol Denat., Parfum (Fragrance), Aqua, Coumarin, Linalool, Benzyl Benzoate.',
    images: g('sandalwood-sillage', 'citrus-oud-28', 'oud-mood-elixir', 'royal-oud-noir'),
    variants: [
      { label: '50 ml', price: 4200, mrp: 5200, stock: 24 },
      { label: '100 ml', price: 5600, mrp: 7000, stock: 15 },
    ],
    badges: [],
    concern: ['Daily wear', 'Layering'],
    rating: 4.6,
    reviewCount: 112,
  },
  {
    slug: 'mystique-noir',
    name: 'Mystique Noir Extrait',
    brand: 'Al Haramain',
    seller: 'attar',
    category: 'fragrance',
    origin: 'Dubai · UAE',
    tagline: 'The house’s flagship — dense, dark, expensive-smelling',
    description:
      'Al Haramain’s most concentrated release: black plum and saffron over aged agarwood, oakmoss and a very dry amber. It smells considerably more expensive than it is, which is the entire reason it sells out every quarter. Sits close for the first ten minutes, then expands for the rest of the day.',
    notes: { top: 'Black Plum, Saffron', heart: 'Aged Agarwood, Oakmoss', base: 'Amber, Tonka, Vetiver' },
    howToUse: 'One spray on each wrist. Let it develop for fifteen minutes before deciding whether you want more.',
    ingredients: 'Alcohol Denat., Parfum (Fragrance), Aqua, Evernia Prunastri Extract, Coumarin, Eugenol, Linalool.',
    images: g('mystique-noir', 'oud-al-layl', 'amber-oud-rouge', 'nuit-blanche'),
    variants: [
      { label: '50 ml', price: 8900, mrp: 11000, stock: 11 },
      { label: '100 ml', price: 11900, mrp: 14900, stock: 4 },
    ],
    badges: ['Best seller', 'Limited stock'],
    concern: ['Evening wear', 'Long lasting', 'Gifting'],
    rating: 4.9,
    reviewCount: 256,
  },
  {
    slug: 'fleur-de-lumiere',
    name: 'Fleur de Lumière',
    brand: 'Lumière Atelier',
    seller: 'noir',
    category: 'fragrance',
    origin: 'Paris · France',
    tagline: 'Jasmine and neroli, bright and green',
    description:
      'Jasmine sambac with green stems still attached — neroli and petitgrain keep it from going syrupy. It is the most wearable floral in the house range and the one most often bought as a first gift. Roughly five hours of wear with moderate projection.',
    notes: { top: 'Neroli, Petitgrain', heart: 'Jasmine Sambac, Magnolia', base: 'Musk, Blonde Woods' },
    howToUse: 'Spray into the air and walk through it if you prefer a softer, more diffuse finish.',
    ingredients: 'Alcohol Denat., Parfum (Fragrance), Aqua, Benzyl Acetate, Linalool, Limonene, Geraniol.',
    images: g('fleur-de-lumiere', 'velvet-bloom', 'rose-attar-absolute', 'royal-oud-noir'),
    variants: [
      { label: '30 ml', price: 3200, mrp: 3900, stock: 29 },
      { label: '50 ml', price: 4600, mrp: 5600, stock: 18 },
    ],
    badges: ['Gift favourite'],
    concern: ['Daily wear', 'Gifting'],
    rating: 4.5,
    reviewCount: 104,
  },
  {
    slug: 'oud-al-layl',
    name: 'Oud Al Layl',
    brand: 'Lattafa Shabab',
    seller: 'attar',
    category: 'fragrance',
    origin: 'Deira, Dubai · UAE',
    tagline: 'Night oud — rose, incense and smoke',
    description:
      'The darker sibling to Oud Mood. Incense and birch tar give it a genuinely smoky edge, with rose softening the middle so it never turns into pure campfire. Cold-weather scent; in heat it can read as heavy. Ten to twelve hours on skin.',
    notes: { top: 'Incense, Black Pepper', heart: 'Rose, Agarwood', base: 'Birch Tar, Amber, Musk' },
    howToUse: 'One spray on a scarf or jacket collar. On bare skin in summer this can overwhelm a small room.',
    ingredients: 'Alcohol Denat., Parfum (Fragrance), Aqua, Eugenol, Isoeugenol, Coumarin, Linalool.',
    images: g('oud-al-layl', 'mystique-noir', 'oud-mood-elixir', 'amber-oud-rouge'),
    variants: [
      { label: '50 ml', price: 3800, mrp: 4700, stock: 26 },
      { label: '100 ml', price: 5200, mrp: 6500, stock: 13 },
    ],
    badges: [],
    concern: ['Evening wear', 'Winter'],
    rating: 4.6,
    reviewCount: 143,
  },

  // ───────────────────────── Skincare ─────────────────────────
  {
    slug: 'hyaluronic-glow-serum',
    name: 'Hyaluronic Glow Serum',
    brand: 'Hanbang Lab',
    seller: 'seoul',
    category: 'skincare',
    origin: 'Seoul · South Korea',
    tagline: 'Five molecular weights of hyaluronic acid',
    description:
      'A lightweight humectant serum that layers five hyaluronic acid weights so hydration sits at different depths rather than all on the surface. It absorbs in about forty seconds and leaves no tack, which matters if you wear makeup over it. Fragrance-free and safe to use twice daily.',
    notes: null,
    howToUse:
      'Apply 3–4 drops to damp skin, morning and night, before moisturiser. On dry skin always seal with a cream — hyaluronic acid without an occlusive can pull moisture out in low humidity.',
    ingredients:
      'Aqua, Glycerin, Sodium Hyaluronate, Sodium Acetylated Hyaluronate, Hydrolyzed Hyaluronic Acid, Panthenol, Betaine, Butylene Glycol, 1,2-Hexanediol, Allantoin.',
    images: g('hyaluronic-glow-serum', 'rose-quartz-mist', 'vitamin-c-serum', 'gold-radiance-serum'),
    variants: [
      { label: '30 ml', price: 1899, mrp: 2400, stock: 62 },
      { label: '50 ml', price: 2650, mrp: 3300, stock: 41 },
    ],
    badges: ['Best seller', 'Fragrance-free'],
    concern: ['Dryness', 'Sensitive skin'],
    rating: 4.7,
    reviewCount: 402,
  },
  {
    slug: 'vitamin-c-serum',
    name: 'Vitamin C Brightening Serum 15%',
    brand: 'Glasswing',
    seller: 'seoul',
    category: 'skincare',
    origin: 'Seoul · South Korea',
    tagline: 'L-ascorbic acid with ferulic acid, in glass',
    description:
      'Fifteen percent L-ascorbic acid buffered with ferulic acid and vitamin E — the combination that actually stays stable long enough to matter. Packed in amber glass with an airless pump because this molecule oxidises the moment it meets light. Expect visible tone evening at six to eight weeks, not six days.',
    notes: null,
    howToUse:
      'Four drops in the morning on clean dry skin, then sunscreen without exception. Start every other day if you have not used a vitamin C before; a mild tingle on the first few uses is normal, stinging is not.',
    ingredients:
      'Aqua, Ascorbic Acid (15%), Propylene Glycol, Ethoxydiglycol, Ferulic Acid, Tocopherol, Panthenol, Sodium Hyaluronate.',
    images: g('vitamin-c-serum', 'gold-radiance-serum', 'hyaluronic-glow-serum', 'marula-face-oil'),
    variants: [
      { label: '30 ml', price: 2150, mrp: 2800, stock: 38 },
      { label: '30 ml × 2 refill', price: 3800, mrp: 5000, stock: 19 },
    ],
    badges: ['Dermatologist tested'],
    concern: ['Pigmentation', 'Dullness'],
    rating: 4.6,
    reviewCount: 288,
  },
  {
    slug: 'barrier-repair-cream',
    name: 'Barrier Repair Cream',
    brand: 'Derma Atelier',
    seller: 'seoul',
    category: 'skincare',
    origin: 'Seoul · South Korea',
    tagline: 'Ceramide NP, cholesterol and fatty acids at 3:1:1',
    description:
      'Built on the 3:1:1 lipid ratio that mirrors what healthy skin actually makes. Rich enough for winter, breathable enough that oily-dehydrated skin can use it year-round. This is the product to reach for after over-exfoliating — most people report the sting gone within two nights.',
    notes: null,
    howToUse:
      'Warm a pea-sized amount and press into damp skin as the final step at night. For a compromised barrier, use it alone for a week — no acids, no retinoids, no vitamin C.',
    ingredients:
      'Aqua, Glycerin, Caprylic/Capric Triglyceride, Cetearyl Alcohol, Ceramide NP, Cholesterol, Squalane, Panthenol, Madecassoside, Allantoin.',
    images: g('barrier-repair-cream', 'ceramide-night-cream', 'azulene-calming-cream', 'bamboo-hydra-gel'),
    variants: [
      { label: '50 ml', price: 2499, mrp: 3200, stock: 47 },
      { label: '80 ml', price: 3400, mrp: 4400, stock: 25 },
    ],
    badges: ['Fragrance-free'],
    concern: ['Sensitive skin', 'Dryness', 'Redness'],
    rating: 4.9,
    reviewCount: 519,
  },
  {
    slug: 'azulene-calming-cream',
    name: 'Azulene Calming Cream',
    brand: 'Blue Iris Lab',
    seller: 'seoul',
    category: 'skincare',
    origin: 'Seoul · South Korea',
    tagline: 'Chamomile-derived azulene for angry skin',
    description:
      'The blue colour is real azulene distilled from chamomile, not dye. Formulated for reactive skin that flushes — think post-facial, post-shave, or the week your barrier gives up. Light gel-cream texture that will not congest, and it sits well under makeup.',
    notes: null,
    howToUse: 'Apply a thin layer to affected areas up to three times daily. Keep refrigerated in summer for extra relief.',
    ingredients:
      'Aqua, Butylene Glycol, Glycerin, Guaiazulene, Chamomilla Recutita Flower Extract, Centella Asiatica Extract, Panthenol, Allantoin, Sodium Hyaluronate.',
    images: g('azulene-calming-cream', 'barrier-repair-cream', 'bamboo-hydra-gel', 'rose-quartz-mist'),
    variants: [
      { label: '50 ml', price: 1750, mrp: 2300, stock: 53 },
      { label: '100 ml', price: 2900, mrp: 3800, stock: 28 },
    ],
    badges: [],
    concern: ['Redness', 'Sensitive skin', 'Acne'],
    rating: 4.7,
    reviewCount: 176,
  },
  {
    slug: 'marula-face-oil',
    name: 'Marula & Rosehip Face Oil',
    brand: 'Nuit Botanica',
    seller: 'noir',
    category: 'skincare',
    origin: 'Paris · France',
    tagline: 'Cold-pressed, unrefined, single-origin marula',
    description:
      'Cold-pressed marula from Limpopo blended with rosehip and a little squalane. High oleic content makes it a genuine dry-skin oil rather than a light finishing one. Four drops at night is the whole routine for a lot of people through Delhi winter.',
    notes: null,
    howToUse:
      'Press 3–4 drops into damp skin as the last step at night. If your skin runs oily, use it only on the cheeks and around the eyes rather than all over.',
    ingredients:
      'Sclerocarya Birrea Seed Oil, Rosa Canina Fruit Oil, Squalane, Simmondsia Chinensis Seed Oil, Tocopherol, Rosmarinus Officinalis Leaf Extract.',
    images: g('marula-face-oil', 'rose-quartz-mist', 'gold-radiance-serum', 'argan-body-elixir'),
    variants: [
      { label: '30 ml', price: 3400, mrp: 4200, stock: 22 },
      { label: '50 ml', price: 4900, mrp: 6100, stock: 12 },
    ],
    badges: ['Clean formula'],
    concern: ['Dryness', 'Ageing'],
    rating: 4.5,
    reviewCount: 91,
  },
  {
    slug: 'gold-radiance-serum',
    name: '24K Gold Radiance Serum',
    brand: 'Aurum Skin',
    seller: 'attar',
    category: 'skincare',
    origin: 'Dubai · UAE',
    tagline: 'Colloidal gold, niacinamide and peptides',
    description:
      'The Dubai spa-counter serum, in the actual retail size rather than the sachet. Niacinamide at 5% and a signal peptide blend do the real work; the colloidal gold gives it the finish that made it famous. Leaves a faint luminous cast that photographs extremely well.',
    notes: null,
    howToUse: 'Two pumps in the evening after cleansing. Pairs well with the barrier cream on top.',
    ingredients:
      'Aqua, Niacinamide (5%), Glycerin, Colloidal Gold, Palmitoyl Tripeptide-1, Palmitoyl Tetrapeptide-7, Sodium Hyaluronate, Panthenol, Adenosine.',
    images: g('gold-radiance-serum', 'vitamin-c-serum', 'hyaluronic-glow-serum', 'marula-face-oil'),
    variants: [
      { label: '30 ml', price: 6200, mrp: 7900, stock: 17 },
      { label: '50 ml', price: 8900, mrp: 11200, stock: 8 },
    ],
    badges: ['Luxury'],
    concern: ['Dullness', 'Ageing', 'Gifting'],
    rating: 4.4,
    reviewCount: 67,
  },
  {
    slug: 'bamboo-hydra-gel',
    name: 'Bamboo Hydra Gel',
    brand: 'Verde Ritual',
    seller: 'seoul',
    category: 'skincare',
    origin: 'Jeju · South Korea',
    tagline: 'Weightless water gel for humid months',
    description:
      'Bamboo sap replaces most of the water in the base, which is why it feels cooling going on. Oil-free and non-comedogenic — this is the moisturiser for Mumbai and Chennai summers, where anything richer just slides off by noon.',
    notes: null,
    howToUse: 'Apply morning and night after serum. Layer twice on very dehydrated days rather than switching to a heavier cream.',
    ingredients:
      'Bambusa Vulgaris Sap, Aqua, Glycerin, Butylene Glycol, Sodium Hyaluronate, Panthenol, Allantoin, Carbomer, 1,2-Hexanediol.',
    images: g('bamboo-hydra-gel', 'azulene-calming-cream', 'barrier-repair-cream', 'ceramide-night-cream'),
    variants: [
      { label: '50 ml', price: 1499, mrp: 1900, stock: 71 },
      { label: '100 ml', price: 2400, mrp: 3100, stock: 44 },
    ],
    badges: ['Oil-free'],
    concern: ['Oiliness', 'Acne'],
    rating: 4.6,
    reviewCount: 233,
  },
  {
    slug: 'ceramide-night-cream',
    name: 'Ceramide Night Cream',
    brand: 'Derma Atelier',
    seller: 'seoul',
    category: 'skincare',
    origin: 'Seoul · South Korea',
    tagline: 'Overnight occlusive with 0.2% retinal',
    description:
      'A richer night counterpart to the barrier cream, with retinaldehyde at a level that is effective without the peeling week that retinol usually costs. Ceramides and squalane cushion the actives. Not for use alongside acids on the same night.',
    notes: null,
    howToUse:
      'Twice weekly to begin, at night only, building to alternate nights over a month. Sunscreen the following morning is not optional. Avoid if pregnant.',
    ingredients:
      'Aqua, Caprylic/Capric Triglyceride, Glycerin, Squalane, Retinal (0.2%), Ceramide NP, Cetearyl Alcohol, Tocopherol, Bisabolol, Panthenol.',
    images: g('ceramide-night-cream', 'barrier-repair-cream', 'gold-radiance-serum', 'azulene-calming-cream'),
    variants: [
      { label: '30 ml', price: 2899, mrp: 3700, stock: 31 },
      { label: '50 ml', price: 4100, mrp: 5300, stock: 16 },
    ],
    badges: ['Dermatologist tested'],
    concern: ['Ageing', 'Texture'],
    rating: 4.8,
    reviewCount: 198,
  },
  {
    slug: 'rose-quartz-mist',
    name: 'Rose Quartz Essence Mist',
    brand: 'Nuit Botanica',
    seller: 'noir',
    category: 'skincare',
    origin: 'Provence · France',
    tagline: 'Damask rose water with a fine-particle pump',
    description:
      'Steam-distilled Damask rose water with glycerin and panthenol, and genuinely one of the better mist heads on the market — the spray is fine enough that it settles rather than beads. Useful mid-flight, mid-afternoon, or to re-wet skin before a serum.',
    notes: null,
    howToUse: 'Mist at arm’s length whenever skin feels tight, then apply serum onto the damp surface.',
    ingredients: 'Rosa Damascena Flower Water, Aqua, Glycerin, Panthenol, Sodium PCA, 1,2-Hexanediol.',
    images: g('rose-quartz-mist', 'hyaluronic-glow-serum', 'marula-face-oil', 'velvet-bloom'),
    variants: [
      { label: '100 ml', price: 1650, mrp: 2100, stock: 58 },
      { label: '200 ml', price: 2600, mrp: 3400, stock: 30 },
    ],
    badges: [],
    concern: ['Dryness', 'Sensitive skin'],
    rating: 4.4,
    reviewCount: 145,
  },

  // ───────────────────────── Makeup ─────────────────────────
  {
    slug: 'velvet-matte-lipstick',
    name: 'Velvet Matte Lipstick',
    brand: 'Maison Rouge',
    seller: 'noir',
    category: 'makeup',
    origin: 'Milan · Italy',
    tagline: 'Full-pigment matte that does not crack',
    description:
      'A true one-swipe matte with enough emollient in the bullet that it does not settle into lip lines by hour two. The shade range was built around warm and olive undertones, which is why the browns and brick reds work on Indian skin where most Western ranges go ashy.',
    notes: null,
    howToUse: 'Line first, then apply from the centre outward. Blot once and reapply for an eight-hour wear.',
    ingredients:
      'Ricinus Communis Seed Oil, Cera Alba, Candelilla Wax, Squalane, Tocopherol, Mica, CI 77491, CI 15850, CI 19140.',
    images: g('velvet-matte-lipstick', 'rouge-eclat', 'coral-crush', 'nude-edit-trio'),
    variants: [
      { label: 'Shade 04 — Brick', price: 1850, mrp: 2400, stock: 46 },
      { label: 'Shade 07 — Cocoa', price: 1850, mrp: 2400, stock: 39 },
      { label: 'Shade 11 — Blood Orange', price: 1850, mrp: 2400, stock: 21 },
    ],
    badges: ['Best seller'],
    concern: ['Long wear'],
    rating: 4.7,
    reviewCount: 312,
  },
  {
    slug: 'satin-lip-duo',
    name: 'Satin Lip Duo',
    brand: 'Maison Rouge',
    seller: 'noir',
    category: 'makeup',
    origin: 'Milan · Italy',
    tagline: 'A satin bullet and matching liner, boxed',
    description:
      'The satin finish sits between a cream and a matte — comfortable enough for all-day wear, still opaque in one pass. Each duo pairs the bullet with a liner mixed to the exact same shade, which is rarer than it should be. Comes gift-boxed.',
    notes: null,
    howToUse: 'Line the full lip rather than just the edges, then fill with the bullet for a wear time close to a matte.',
    ingredients:
      'Ricinus Communis Seed Oil, Cera Alba, Simmondsia Chinensis Seed Oil, Tocopherol, Mica, CI 77491, CI 45410, CI 15850.',
    images: g('satin-lip-duo', 'nude-edit-trio', 'lip-gloss-edit', 'velvet-matte-lipstick'),
    variants: [
      { label: 'Rosewood duo', price: 2400, mrp: 3100, stock: 27 },
      { label: 'Terracotta duo', price: 2400, mrp: 3100, stock: 18 },
    ],
    badges: ['Gift favourite'],
    concern: ['Gifting'],
    rating: 4.5,
    reviewCount: 124,
  },
  {
    slug: 'rouge-eclat',
    name: 'Rouge Éclat Lipstick',
    brand: 'Maison Rouge',
    seller: 'noir',
    category: 'makeup',
    origin: 'Milan · Italy',
    tagline: 'High-shine reds with a hydrating core',
    description:
      'Built for people who want a red but cannot tolerate a drying matte. A hydrating core of shea and squalane sits inside a pigmented shell, so shine and colour payoff arrive together. Needs reapplying after a meal — that is the trade for the comfort.',
    notes: null,
    howToUse: 'Apply straight from the bullet, no liner needed. Blot on a tissue if you want a stained finish instead.',
    ingredients:
      'Ricinus Communis Seed Oil, Butyrospermum Parkii Butter, Squalane, Cera Alba, Tocopherol, Mica, CI 15850, CI 45410.',
    images: g('rouge-eclat', 'velvet-matte-lipstick', 'coral-crush', 'lip-gloss-edit'),
    variants: [
      { label: 'Éclat 01 — Classic Red', price: 1999, mrp: 2600, stock: 34 },
      { label: 'Éclat 05 — Deep Cherry', price: 1999, mrp: 2600, stock: 29 },
    ],
    badges: [],
    concern: ['Dryness', 'Long wear'],
    rating: 4.4,
    reviewCount: 158,
  },
  {
    slug: 'lip-gloss-edit',
    name: 'The Lip Gloss Edit — Set of 4',
    brand: 'Glasswing',
    seller: 'seoul',
    category: 'makeup',
    origin: 'Seoul · South Korea',
    tagline: 'Four non-sticky glosses in a zip case',
    description:
      'Four glosses in the shades people actually re-buy — clear, peach, rose and a deep berry. The base is a lightweight polybutene rather than the tacky syrup most glosses use, so hair does not stick to it in wind. Case included.',
    notes: null,
    howToUse: 'Wear alone for a wash of colour or over a matte lipstick to convert it to a satin finish.',
    ingredients: 'Polybutene, Hydrogenated Polyisobutene, Squalane, Tocopherol, Mica, CI 15850, CI 45410, CI 77491.',
    images: g('lip-gloss-edit', 'satin-lip-duo', 'nude-edit-trio', 'rouge-eclat'),
    variants: [{ label: 'Set of 4 × 5 ml', price: 2750, mrp: 3600, stock: 36 }],
    badges: ['Value set'],
    concern: ['Gifting'],
    rating: 4.3,
    reviewCount: 97,
  },
  {
    slug: 'coral-crush',
    name: 'Coral Crush Lip & Cheek',
    brand: 'Maison Rouge',
    seller: 'noir',
    category: 'makeup',
    origin: 'Milan · Italy',
    tagline: 'One stick, lips and cheeks',
    description:
      'A cream-to-powder stick that blends out sheer on the cheek and builds opaque on the lip. Coral is the most forgiving shade family across skin tones, and this one leans warm rather than neon. Fits in the smallest bag you own.',
    notes: null,
    howToUse: 'Three dots on the cheek, blended out with fingers within about ten seconds — it sets fast.',
    ingredients:
      'Caprylic/Capric Triglyceride, Cera Alba, Silica, Squalane, Tocopherol, Mica, CI 45410, CI 77491, CI 77891.',
    images: g('coral-crush', 'rouge-eclat', 'velvet-matte-lipstick', 'satin-lip-duo'),
    variants: [
      { label: 'Coral', price: 1650, mrp: 2100, stock: 42 },
      { label: 'Warm Rose', price: 1650, mrp: 2100, stock: 37 },
    ],
    badges: ['Multi-use'],
    concern: ['Daily wear'],
    rating: 4.6,
    reviewCount: 186,
  },
  {
    slug: 'nude-edit-trio',
    name: 'The Nude Edit — Trio',
    brand: 'Maison Rouge',
    seller: 'noir',
    category: 'makeup',
    origin: 'Milan · Italy',
    tagline: 'Three nudes mixed for deeper undertones',
    description:
      'Most nude sets are built for pale skin and turn grey on everyone else. These three — a warm caramel, a rosy brown and a deep mocha — were mixed specifically for medium to deep complexions. Satin finish, boxed as a set.',
    notes: null,
    howToUse: 'Wear the caramel alone for daytime; layer the mocha over it to deepen for evening.',
    ingredients:
      'Ricinus Communis Seed Oil, Cera Alba, Butyrospermum Parkii Butter, Tocopherol, Mica, CI 77491, CI 77492, CI 77499.',
    images: g('nude-edit-trio', 'satin-lip-duo', 'lip-gloss-edit', 'coral-crush'),
    variants: [{ label: 'Trio × 3.5 g', price: 3200, mrp: 4300, stock: 24 }],
    badges: ['Editor’s pick', 'Value set'],
    concern: ['Gifting', 'Daily wear'],
    rating: 4.8,
    reviewCount: 211,
  },

  // ───────────────────────── Bath & Body ─────────────────────────
  {
    slug: 'argan-body-elixir',
    name: 'Argan Body Elixir',
    brand: 'Hammam Rituals',
    seller: 'noir',
    category: 'bath-body',
    origin: 'Marrakech · Morocco',
    tagline: 'Cold-pressed argan from a women’s cooperative',
    description:
      'Unrefined argan pressed by a cooperative outside Essaouira, blended with a little sweet almond so it spreads further. Sinks in within two minutes rather than sitting on the skin. The faint nutty smell is the oil being genuinely unrefined — it fades in about ten minutes.',
    notes: null,
    howToUse: 'Apply to damp skin straight out of the shower. A five-rupee-coin amount covers both arms.',
    ingredients: 'Argania Spinosa Kernel Oil, Prunus Amygdalus Dulcis Oil, Tocopherol, Parfum, Limonene, Linalool.',
    images: g('argan-body-elixir', 'hammam-body-polish', 'spa-mineral-soak', 'marula-face-oil'),
    variants: [
      { label: '100 ml', price: 2300, mrp: 2900, stock: 33 },
      { label: '200 ml', price: 3700, mrp: 4800, stock: 19 },
    ],
    badges: ['Fair trade'],
    concern: ['Dryness'],
    rating: 4.7,
    reviewCount: 154,
  },
  {
    slug: 'gua-sha-ritual-set',
    name: 'Gua Sha Ritual Set',
    brand: 'Verde Ritual',
    seller: 'seoul',
    category: 'bath-body',
    origin: 'Jeju · South Korea',
    tagline: 'Rose quartz tool, facial oil and pouch',
    description:
      'A genuine rose quartz tool — heavy, cold, and cut with a proper contour edge rather than the thin plates that snap. Comes with a slip oil so the stone glides instead of dragging, plus a padded travel pouch. Complete gift on its own.',
    notes: null,
    howToUse:
      'Always apply the oil first — dragging a stone across dry skin creates the redness gua sha is meant to reduce. Work upward and outward, three passes per section, light pressure.',
    ingredients:
      'Tool: Rose Quartz. Oil: Camellia Japonica Seed Oil, Squalane, Simmondsia Chinensis Seed Oil, Tocopherol.',
    images: g('gua-sha-ritual-set', 'spa-mineral-soak', 'marula-face-oil', 'hammam-body-polish'),
    variants: [{ label: 'Set — tool + 30 ml oil', price: 3600, mrp: 4700, stock: 21 }],
    badges: ['Gift favourite', 'Value set'],
    concern: ['Gifting', 'Puffiness'],
    rating: 4.5,
    reviewCount: 132,
  },
  {
    slug: 'hammam-body-polish',
    name: 'Hammam Black Soap Polish',
    brand: 'Hammam Rituals',
    seller: 'noir',
    category: 'bath-body',
    origin: 'Marrakech · Morocco',
    tagline: 'Beldi black soap with eucalyptus',
    description:
      'Traditional olive-based beldi soap, the same paste used in Moroccan hammams. It does not foam much — that is correct. Left on for five minutes it softens the skin enough that a kessa mitt lifts away a startling amount of dead surface layer.',
    notes: null,
    howToUse:
      'Apply to wet skin in a steamy bathroom, leave five minutes, then scrub off with a kessa mitt. Once a week at most, and never on the day you shave or wax.',
    ingredients: 'Olea Europaea Fruit Oil, Aqua, Potassium Hydroxide, Eucalyptus Globulus Leaf Oil, Glycerin.',
    images: g('hammam-body-polish', 'spa-mineral-soak', 'argan-body-elixir', 'gua-sha-ritual-set'),
    variants: [
      { label: '200 g', price: 1900, mrp: 2500, stock: 40 },
      { label: '200 g + kessa mitt', price: 2400, mrp: 3200, stock: 23 },
    ],
    badges: [],
    concern: ['Texture'],
    rating: 4.6,
    reviewCount: 108,
  },
  {
    slug: 'spa-mineral-soak',
    name: 'Dead Sea Mineral Soak',
    brand: 'Hammam Rituals',
    seller: 'attar',
    category: 'bath-body',
    origin: 'Jordan Valley · Levant',
    tagline: 'Magnesium-rich salts with lavender',
    description:
      'Coarse Dead Sea salt — high magnesium, high potassium — with lavender and a little bergamot. Genuinely useful after long training days or standing shifts. The crystals are large, so they dissolve slowly enough that the bath stays scented to the end.',
    notes: null,
    howToUse: 'Two generous handfuls under running hot water. Soak twenty minutes and rinse afterwards; the mineral residue can feel tacky if left on.',
    ingredients: 'Maris Sal (Dead Sea Salt), Magnesium Chloride, Lavandula Angustifolia Oil, Citrus Bergamia Oil, Limonene, Linalool.',
    images: g('spa-mineral-soak', 'hammam-body-polish', 'argan-body-elixir', 'gua-sha-ritual-set'),
    variants: [
      { label: '500 g', price: 1450, mrp: 1900, stock: 51 },
      { label: '1 kg', price: 2300, mrp: 3100, stock: 29 },
    ],
    badges: [],
    concern: ['Relaxation'],
    rating: 4.4,
    reviewCount: 76,
  },
]

/** Seeded reviews, keyed by product slug. */
export const REVIEWS = {
  'oud-mood-elixir': [
    { author: 'Zoya R.', rating: 5, title: 'Smells like the souk, genuinely', body: 'Bought this in Dubai two years ago and could never find it here at a sane price. Same batch quality, arrived sealed. One spray lasts my entire workday.', city: 'Hyderabad' },
    { author: 'Karan M.', rating: 4, title: 'Strong — go easy', body: 'Beautiful but I over-applied the first time and my car smelled of it for three days. One spray is plenty.', city: 'Pune' },
    { author: 'Meher S.', rating: 5, title: 'My signature now', body: 'The saffron opening is gorgeous. Got two compliments in the first week.', city: 'Mumbai' },
  ],
  'barrier-repair-cream': [
    { author: 'Ananya D.', rating: 5, title: 'Fixed my over-exfoliated skin', body: 'I had wrecked my barrier with too many acids. Used this alone for a week as instructed and the stinging stopped by the second night.', city: 'Bengaluru' },
    { author: 'Rhea P.', rating: 5, title: 'Worth the import price', body: 'Cheaper than buying it off resellers and the expiry was 2027. Packaging was sealed and boxed properly.', city: 'Delhi' },
  ],
  'mystique-noir': [
    { author: 'Imran K.', rating: 5, title: 'Smells like a ₹40k bottle', body: 'Wore it to a wedding and three people asked. The drydown after six hours is the best part.', city: 'Lucknow' },
  ],
  'velvet-matte-lipstick': [
    { author: 'Sneha V.', rating: 5, title: 'Shade 07 on Indian skin', body: 'Finally a nude-brown that does not go grey on medium skin. Does not crack after eating.', city: 'Chennai' },
    { author: 'Fatima A.', rating: 4, title: 'Good, slightly drying by hour six', body: 'Colour payoff is excellent. I put balm underneath and it is fine all day.', city: 'Kolkata' },
  ],
  'hyaluronic-glow-serum': [
    { author: 'Divya N.', rating: 5, title: 'Absorbs properly', body: 'No stickiness, which was my problem with every other HA serum. Makeup sits fine over it.', city: 'Kochi' },
  ],
  'rose-attar-absolute': [
    { author: 'Nusrat J.', rating: 5, title: 'Real attar, not oil-in-alcohol', body: 'You can tell immediately — it is thick and there is no alcohol sting. Lasts on a scarf for days.', city: 'Bhopal' },
  ],
}
