/**
 * Self-hosts the two webfonts so the storefront renders correctly offline.
 * Pulls woff2 files from the Google Fonts CDN and writes a local @font-face sheet.
 */
import { mkdir, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const OUT = join(ROOT, 'client', 'public', 'fonts')

// A modern UA is required or Google serves legacy ttf instead of woff2.
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36'

const FAMILIES = [
  { css: 'Playfair+Display:wght@400;500;600;700', file: 'playfair' },
  { css: 'Inter:wght@400;500;600;700', file: 'inter' },
]

async function main() {
  await mkdir(OUT, { recursive: true })
  const faces = []

  for (const family of FAMILIES) {
    const url = `https://fonts.googleapis.com/css2?family=${family.css}&display=swap`
    const css = await fetch(url, { headers: { 'User-Agent': UA } }).then((r) => r.text())

    // Keep only the latin block — we don't need cyrillic/vietnamese subsets.
    const blocks = css.split('/*').filter((b) => b.trim().startsWith('latin */'))
    let i = 0

    for (const block of blocks) {
      const src = block.match(/url\((https:[^)]+\.woff2)\)/)?.[1]
      const weight = block.match(/font-weight:\s*(\d+)/)?.[1] ?? '400'
      const style = block.match(/font-style:\s*(\w+)/)?.[1] ?? 'normal'
      const name = block.match(/font-family:\s*'([^']+)'/)?.[1]
      if (!src || !name) continue

      const filename = `${family.file}-${weight}${style === 'italic' ? '-italic' : ''}.woff2`
      const buf = Buffer.from(await fetch(src, { headers: { 'User-Agent': UA } }).then((r) => r.arrayBuffer()))
      await writeFile(join(OUT, filename), buf)
      console.log(`  ${name} ${weight} ${style.padEnd(6)} ${(buf.length / 1024).toFixed(0)} kB  ${filename}`)

      faces.push(
        `@font-face {\n  font-family: '${name}';\n  font-style: ${style};\n  font-weight: ${weight};\n  font-display: swap;\n  src: url('/fonts/${filename}') format('woff2');\n}`
      )
      i++
    }
    if (!i) console.warn(`  ! no latin faces parsed for ${family.css}`)
  }

  await writeFile(
    join(OUT, 'fonts.css'),
    `/* Generated by scripts/download-fonts.mjs — do not edit by hand. */\n\n${faces.join('\n\n')}\n`
  )
  console.log(`\nWrote ${faces.length} @font-face rules to client/public/fonts/fonts.css`)
}

main()
